### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Eikosa** [paulbricman/autocards#36]
```
>>> a = Autocards()
Loading backend, this can take some time...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\USER\autocards\autocards.py", line 79, in __init__
    self.qg = qg_pipeline('question-generation',
  File "C:\Users\USER\autocards\pipelines.py", line 360, in qg_pipeline
    tokenizer = AutoTokenizer.from_pretrained(tokenizer)
  File "C:\Users\USER\AppData\Roaming\Python\Python39\site-packages\transformers\models\auto\tokenization_auto.py", line 435, in from_pretrained
    return tokenizer_class_fast.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
  File "C:\Users\USER\AppData\Roaming\Python\Python39\site-packages\transformers\tokenization_utils_base.py", line 1719, in from_pretrained
    return cls._from_pretrained(
  File "C:\Users\USER\AppData\Roaming\Python\Python39\site-packages\transformers\tokenization_utils_base.py", line 1791, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "C:\Users\USER\AppData\Roaming\Python\Python39\site-packages\transformers\models\t5\tokenization_t5_fast.py", line 128, in __init__
    super().__init__(
  File "C:\Users\USER\AppData\Roaming\Python\Python39\site-packages\transformers\tokenization_utils_fast.py", line 105, in __init__
    raise ValueError(
ValueError: Couldn't instantiate the backend tokenizer from one of:
(1) a `tokenizers` library serialization file,
(2) a slow tokenizer instance to convert or
(3) an equivalent slow tokenizer class to instantiate and convert.
You need to have sentencepiece installed to convert a slow tokenizer to a fast one.
>>> a.consume_var("a")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'a' is not defined
```

**Comment by thiswillbeyourgithub** [comment]
Related to #35.

I think you should try with earlier versions of transformers.

**Comment by thiswillbeyourgithub** [comment]
Close because solution in #35

**Comment by Eikosa** [comment]
unfortunately i can't install transformers v3

**Comment by thiswillbeyourgithub** [comment]
Please be more explicit.
